#spring.application.name=financetracker

# URL de conexión a la base de datos que creamos en el Paso 1
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker
# Tu usuario de MySQL (por defecto suele ser root)
spring.datasource.username=root
# Tu contraseña de MySQL (Cámbiala por la tuya)
spring.datasource.password=

# Configuración mágica de JPA/Hibernate
# 'update' hace que Spring Boot cree o actualice las tablas automáticamente según tu código Java
spring.jpa.hibernate.ddl-auto=update
# Esto mostrará en la consola el código SQL que Spring Boot genera por detrás
spring.jpa.show-sql=true