#spring.application.name=financetracker

# URL de conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker
# Tu usuario de MySQL
spring.datasource.username=root
# Tu contrasena de MySQL
spring.datasource.password=

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
# Muestra en consola el codigo SQL
spring.jpa.show-sql=true