# URL de conexión a la base de datos (Usa la variable de Render o localhost por defecto)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:finance_tracker}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Usuario de MySQL (Usa la variable de Render o root por defecto)
spring.datasource.username=${DB_USER:root}

# Contraseña de MySQL (Usa la variable de Render o vacío por defecto)
spring.datasource.password=${DB_PASSWORD:}

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola el código SQL (Puedes dejarlo en true o cambiarlo a false en producción)
spring.jpa.show-sql=true